# =============================================================================
# WHAT: gRPC and Protocol Buffers (protobuf) — Python Reference
# WHY:  gRPC gives you typed, high-performance RPC with streaming built in.
#       Protobuf serializes 3–10x smaller than JSON and 10–100x faster to
#       parse. The combination dominates internal service communication at
#       Google, Netflix, Uber, and most large microservice platforms.
# LEVEL: Intermediate → Advanced
# =============================================================================
#
# CONCEPT OVERVIEW
# ----------------
# Protocol Buffers (protobuf) is a language-neutral binary serialization format.
# You define message types in .proto files, then compile them to Python (or any
# other language) with protoc. The generated code handles encoding/decoding.
#
# gRPC is an RPC framework that uses:
#   - HTTP/2 as the transport (multiplexing, header compression, push)
#   - Protobuf as the default serialization format
#   - A .proto service definition as the contract
#
# Four call types:
#   Unary             — single request, single response (like HTTP)
#   Server streaming  — single request, stream of responses
#   Client streaming  — stream of requests, single response
#   Bidirectional     — stream of requests, stream of responses (chat, telemetry)
#
# PRODUCTION USE CASE
# -------------------
# A ride-sharing platform uses gRPC internally:
#   - Driver location service: client-streaming (driver sends GPS pings)
#   - ETA service: unary (request trip route, get back ETA)
#   - Surge pricing feed: server-streaming (clients receive pricing updates)
#   - Live tracking: bidirectional (driver ↔ passenger real-time updates)
# The HTTP/JSON API exposed to mobile apps is transcoded through grpc-gateway.
#
# COMMON MISTAKES
# ---------------
# 1. Changing a field number → permanently breaks wire compatibility
# 2. Using gRPC status code 2 (UNKNOWN) for app errors → use specific codes
# 3. Not setting deadlines on every client call → hang forever on server crash
# 4. Ignoring channel state; creating a new channel per RPC → huge overhead
# 5. Streaming without flow control → OOM on slow consumers
# 6. Forgetting to call channel.close() → leaking connections
# =============================================================================

# ---------------------------------------------------------------------------
# Standard library
# ---------------------------------------------------------------------------
import logging
import time
from concurrent import futures
from datetime import timedelta
from typing import Iterator

# ---------------------------------------------------------------------------
# gRPC runtime — pip install grpcio grpcio-tools grpcio-reflection grpcio-health-checking
# ---------------------------------------------------------------------------
import grpc
import grpc.experimental.gevent as grpc_gevent  # optional: gevent support

# ---------------------------------------------------------------------------
# These would be generated by protoc in a real project.
# We define stub classes here so this file runs as a pure reference.
# Real command: python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. service.proto
# ---------------------------------------------------------------------------
CMD_PROTOC = (
    "python -m grpc_tools.protoc "
    "-I proto/ "
    "--python_out=generated/ "
    "--grpc_python_out=generated/ "
    "proto/order_service.proto"
)

# ---------------------------------------------------------------------------
# Logging setup — gRPC's internal logger uses 'grpc'
# ---------------------------------------------------------------------------
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


# =============================================================================
# PART 1 — PROTOCOL BUFFERS SYNTAX (shown as Python strings for reference)
# =============================================================================
# In a real project these live in *.proto files and are compiled.
# Field numbers (1, 2, 3...) are the wire identity — they NEVER change.
# Names can change (though that's a bad idea); numbers cannot.
# =============================================================================

PROTO_EXAMPLE = """
syntax = "proto3";                     // proto3 is the modern default

// Package prevents name collisions when importing across services
package order.v2;

// Go package path (generated code configuration)
option go_package = "github.com/example/order/gen/go";

import "google/protobuf/timestamp.proto";   // Well-known types
import "google/protobuf/any.proto";         // Embed arbitrary message types

// ─── Scalar types available in proto3 ────────────────────────────────────────
// double, float                → Python float
// int32, int64                 → Python int  (negative values waste space; use sint32/sint64)
// uint32, uint64               → Python int  (always non-negative)
// sint32, sint64               → Python int  (efficient for negative numbers; uses zigzag encoding)
// fixed32, fixed64             → Python int  (constant 4/8 bytes; good for ids > 2^28)
// bool                         → Python bool
// string                       → Python str  (must be valid UTF-8)
// bytes                        → Python bytes (arbitrary binary)

// ─── Message definition ───────────────────────────────────────────────────────
message OrderItem {
    string sku = 1;              // Field number 1 — THE WIRE IDENTITY. Never reuse.
    int32 quantity = 2;          // If you remove this field, reserve the number: reserved 2;
    double unit_price_usd = 3;
}

message CreateOrderRequest {
    int64 customer_id = 1;
    repeated OrderItem items = 2;   // 'repeated' = list; zero items allowed in proto3

    // 'oneof' — at most one of these fields can be set at a time
    oneof delivery_preference {
        string delivery_address = 3;
        int64 pickup_location_id = 4;
    }

    map<string, string> metadata = 5;   // String-keyed map; value can be any type

    google.protobuf.Timestamp requested_delivery = 6;  // Structured timestamp
}

enum OrderStatus {
    ORDER_STATUS_UNSPECIFIED = 0;   // proto3 REQUIRES enum value 0 (default)
    ORDER_STATUS_PENDING = 1;
    ORDER_STATUS_CONFIRMED = 2;
    ORDER_STATUS_SHIPPED = 3;
    ORDER_STATUS_DELIVERED = 4;
    ORDER_STATUS_CANCELLED = 5;
}

message OrderResponse {
    string order_id = 1;
    OrderStatus status = 2;
    int64 customer_id = 3;
    repeated OrderItem items = 4;
    google.protobuf.Timestamp created_at = 5;
    google.protobuf.Any extension_data = 6;  // Escape hatch for polymorphic payloads

    // Fields reserved so they can never be accidentally reused
    reserved 7, 8;                 // reserve by field number
    reserved "old_field_name";     // reserve by name
}

// ─── Service definition ────────────────────────────────────────────────────────
service OrderService {
    // Unary: one request, one response
    rpc CreateOrder (CreateOrderRequest) returns (OrderResponse);

    // Server streaming: one request, stream of responses
    rpc WatchOrderStatus (WatchOrderRequest) returns (stream OrderStatusUpdate);

    // Client streaming: stream of requests, one response
    rpc BatchCreateOrders (stream CreateOrderRequest) returns (BatchOrderResponse);

    // Bidirectional streaming: stream ↔ stream
    rpc OrderChat (stream ChatMessage) returns (stream ChatMessage);
}
"""

# proto2 vs proto3 key differences
PROTO2_VS_PROTO3 = {
    "default_values": {
        "proto2": "Fields have no default; you can tell if a field was set",
        "proto3": "Missing fields default to zero values (0, '', false, [])",
    },
    "required_keyword": {
        "proto2": "Fields can be required, optional, or repeated",
        "proto3": "No required fields; all singular fields are effectively optional",
    },
    "extensions": {
        "proto2": "Supported (allows adding fields to messages you don't own)",
        "proto3": "Removed; use Any or oneof instead",
    },
    "field_presence": {
        "proto2": "Always known (optional fields have hasFoo() methods)",
        "proto3": "Not tracked by default; use 'optional' keyword in proto3 to get hasFoo()",
    },
    "recommendation": "Use proto3 for all new projects unless you specifically need proto2 semantics",
}


# =============================================================================
# PART 2 — gRPC SERVER IMPLEMENTATION
# =============================================================================
# The servicer class inherits from the generated *Servicer base class.
# Each RPC method receives a context object carrying metadata, deadline, etc.
# =============================================================================

class OrderServiceServicer:
    """
    Concrete implementation of the OrderService gRPC service.
    In a real project this inherits from order_service_pb2_grpc.OrderServiceServicer.
    The generated base class provides default implementations that return
    UNIMPLEMENTED for every method — you override only what you support.
    """

    # ── Unary RPC ──────────────────────────────────────────────────────────────
    def CreateOrder(self, request, context):
        """
        request: CreateOrderRequest protobuf message
        context: grpc.ServicerContext — abort, set_trailing_metadata, etc.
        """
        logger.info("CreateOrder called for customer_id=%s", request.customer_id)

        # Validate input; if invalid, abort with a gRPC error code
        if not request.items:
            # INVALID_ARGUMENT (3) = client sent bad data; client should not retry
            context.abort(
                grpc.StatusCode.INVALID_ARGUMENT,
                "At least one item is required",
            )
            return  # abort() does not stop execution — must return explicitly

        # Check if the deadline has already passed before doing expensive work
        if context.time_remaining() is not None and context.time_remaining() < 0.1:
            context.abort(grpc.StatusCode.DEADLINE_EXCEEDED, "Deadline already elapsed")
            return

        # Simulate DB write
        order_id = f"ORD-{int(time.time())}"

        # Attach trailing metadata (analogous to HTTP response headers)
        context.set_trailing_metadata([
            ("x-request-id", order_id),
            ("x-region", "us-west-2"),
        ])

        # Return a response message (would be order_service_pb2.OrderResponse)
        return {"order_id": order_id, "status": 1, "customer_id": request.customer_id}

    # ── Server-streaming RPC ───────────────────────────────────────────────────
    def WatchOrderStatus(self, request, context) -> Iterator[dict]:
        """
        Yields multiple responses. The client receives each as it's sent.
        Use case: long-lived watch; push status updates as they happen.
        """
        order_id = request.order_id  # type: ignore[attr-defined]
        statuses = ["PENDING", "CONFIRMED", "SHIPPED", "DELIVERED"]

        for status in statuses:
            # Check if the client cancelled the stream (they closed the connection)
            if not context.is_active():
                logger.info("Client cancelled WatchOrderStatus stream")
                return

            yield {"order_id": order_id, "status": status}
            time.sleep(1)  # In prod: sleep until a DB change-event arrives

    # ── Client-streaming RPC ───────────────────────────────────────────────────
    def BatchCreateOrders(self, request_iterator, context) -> dict:
        """
        Iterates over a stream of CreateOrderRequest messages from the client.
        Returns a single summary response when the stream is exhausted.
        Use case: bulk import, chunked file uploads.
        """
        created_ids = []
        errors = []

        for i, request in enumerate(request_iterator):
            try:
                # Process each request as it arrives
                order_id = f"ORD-BATCH-{i}"
                created_ids.append(order_id)
            except Exception as e:
                errors.append(str(e))

        return {"created_order_ids": created_ids, "error_count": len(errors)}

    # ── Bidirectional streaming RPC ────────────────────────────────────────────
    def OrderChat(self, request_iterator, context) -> Iterator[dict]:
        """
        Receives messages from the client stream and yields responses.
        Both sides send independently — full-duplex.
        Use case: real-time driver ↔ passenger messaging.
        """
        for message in request_iterator:
            if not context.is_active():
                break
            # Echo back with a timestamp — real impl would route to other party
            yield {
                "sender": "system",
                "content": f"Received: {message.content}",  # type: ignore[attr-defined]
                "timestamp": int(time.time()),
            }


# =============================================================================
# PART 3 — CREATING AND RUNNING THE SERVER
# =============================================================================

def serve(port: int = 50051, max_workers: int = 10) -> None:
    """
    Start the gRPC server.
    ThreadPoolExecutor is the default; for async use grpc.aio.server().
    """
    # Create a server with a thread pool
    server = grpc.server(
        futures.ThreadPoolExecutor(max_workers=max_workers),
        # Interceptors run before/after each RPC — good for auth, logging, tracing
        interceptors=[],
        options=[
            # Maximum message size to receive (default 4MB)
            ("grpc.max_receive_message_length", 16 * 1024 * 1024),  # 16 MB
            # Maximum message size to send
            ("grpc.max_send_message_length", 16 * 1024 * 1024),
            # Keepalive: send ping after 30s of inactivity
            ("grpc.keepalive_time_ms", 30_000),
            # Close connection if no ping ack within 10s
            ("grpc.keepalive_timeout_ms", 10_000),
        ],
    )

    # Register the servicer — in real code:
    # order_service_pb2_grpc.add_OrderServiceServicer_to_server(OrderServiceServicer(), server)

    # Bind to port; insecure for dev, TLS for production
    server.add_insecure_port(f"[::]:{port}")

    # For production TLS:
    # with open("server.key", "rb") as f: private_key = f.read()
    # with open("server.crt", "rb") as f: cert_chain = f.read()
    # credentials = grpc.ssl_server_credentials([(private_key, cert_chain)])
    # server.add_secure_port(f"[::]:{port}", credentials)

    server.start()
    logger.info("gRPC server listening on port %d", port)

    try:
        server.wait_for_termination()
    except KeyboardInterrupt:
        # Graceful shutdown: finish in-flight RPCs, then stop
        server.stop(grace=5)  # 5 seconds grace period


# =============================================================================
# PART 4 — CLIENT USAGE: CHANNEL, STUB, DEADLINES
# =============================================================================

def create_channel(host: str = "localhost", port: int = 50051) -> grpc.Channel:
    """
    Create a reusable gRPC channel. ONE channel per target; share across threads.
    Channels are thread-safe and maintain a connection pool internally.
    """
    # Insecure (dev/internal):
    channel = grpc.insecure_channel(
        f"{host}:{port}",
        options=[
            # Initial backoff for retry (default 1s)
            ("grpc.initial_reconnect_backoff_ms", 500),
            # Maximum backoff cap
            ("grpc.max_reconnect_backoff_ms", 5_000),
        ],
    )

    # Wait until the channel is ready (or timeout)
    try:
        grpc.channel_ready_future(channel).result(timeout=10)
        logger.info("Channel connected to %s:%d", host, port)
    except grpc.FutureTimeoutError:
        logger.error("Could not connect to gRPC server within 10 seconds")
        raise

    return channel


def call_create_order_with_deadline(channel: grpc.Channel) -> None:
    """
    Demonstrate setting a deadline on every outgoing RPC.
    NEVER make gRPC calls without a deadline — servers can hang forever otherwise.
    """
    # Create a stub from the generated module:
    # stub = order_service_pb2_grpc.OrderServiceStub(channel)
    # For this reference file, we show the pattern conceptually:

    deadline_seconds = 5.0  # This RPC must complete within 5 seconds

    try:
        # timeout= sets an absolute deadline from now
        # response = stub.CreateOrder(request, timeout=deadline_seconds)
        logger.info("RPC would be called with %.1f second deadline", deadline_seconds)
    except grpc.RpcError as e:
        # e.code() returns a grpc.StatusCode; e.details() returns the message
        handle_grpc_error(e)  # type: ignore[arg-type]


def handle_grpc_error(error: grpc.RpcError) -> None:
    """
    Centralised gRPC error handler. gRPC has its own status code space —
    do NOT map these to HTTP status codes in your business logic.
    """
    code = error.code()          # grpc.StatusCode enum
    details = error.details()    # Human-readable error message
    # error.trailing_metadata() → key-value pairs sent by the server

    # Map of gRPC status codes and what they mean for retry strategy
    RETRY_CODES = {
        grpc.StatusCode.UNAVAILABLE,      # Server is down; retry with backoff
        grpc.StatusCode.RESOURCE_EXHAUSTED,  # Rate limited; retry after delay
        grpc.StatusCode.DEADLINE_EXCEEDED,   # Timeout; consider retry with fresh deadline
    }

    NO_RETRY_CODES = {
        grpc.StatusCode.INVALID_ARGUMENT,   # Bad client data; fix the request
        grpc.StatusCode.NOT_FOUND,          # Resource doesn't exist
        grpc.StatusCode.ALREADY_EXISTS,     # Duplicate; check before creating
        grpc.StatusCode.PERMISSION_DENIED,  # Auth failure; fix credentials
        grpc.StatusCode.UNAUTHENTICATED,    # Missing credentials
        grpc.StatusCode.UNIMPLEMENTED,      # Server doesn't support this method
    }

    if code in RETRY_CODES:
        logger.warning("Retryable gRPC error [%s]: %s", code.name, details)
    elif code in NO_RETRY_CODES:
        logger.error("Non-retryable gRPC error [%s]: %s", code.name, details)
        raise  # Re-raise; caller should not retry
    else:
        logger.error("Unknown gRPC error [%s]: %s", code.name, details)


# =============================================================================
# PART 5 — METADATA (the gRPC equivalent of HTTP headers)
# =============================================================================
# Metadata is key-value pairs sent alongside an RPC call.
# Keys ending in -bin carry binary values (base64-encoded on the wire).
# =============================================================================

def call_with_metadata(channel: grpc.Channel) -> None:
    """Send authentication and tracing metadata with an RPC."""
    metadata = [
        ("authorization", "Bearer eyJhbGciOiJSUzI1NiJ9..."),  # JWT token
        ("x-request-id", "req-abc-123"),                        # Tracing ID
        ("x-correlation-id", "corr-xyz-456"),
        # Binary metadata key MUST end with -bin
        ("custom-data-bin", b"\x00\x01\x02\x03"),
    ]

    # Pass metadata as the 'metadata' kwarg:
    # response = stub.CreateOrder(request, metadata=metadata, timeout=5.0)
    logger.info("Would send %d metadata entries", len(metadata))


# =============================================================================
# PART 6 — INTERCEPTORS (middleware for gRPC)
# =============================================================================
# Interceptors wrap every RPC call. Use for: auth, logging, metrics, tracing.
# Client-side and server-side interceptors are registered separately.
# =============================================================================

class LoggingClientInterceptor(grpc.UnaryUnaryClientInterceptor):
    """
    Logs every outgoing unary RPC with timing.
    For streaming RPCs you'd implement UnaryStreamClientInterceptor,
    StreamUnaryClientInterceptor, or StreamStreamClientInterceptor.
    """

    def intercept_unary_unary(self, continuation, client_call_details, request):
        method = client_call_details.method  # e.g., "/order.v2.OrderService/CreateOrder"
        start = time.monotonic()
        logger.info("→ gRPC %s", method)

        try:
            response = continuation(client_call_details, request)
            elapsed = time.monotonic() - start
            logger.info("← gRPC %s completed in %.3fs", method, elapsed)
            return response
        except grpc.RpcError as e:
            elapsed = time.monotonic() - start
            logger.error("← gRPC %s failed [%s] in %.3fs", method, e.code(), elapsed)
            raise


class AuthServerInterceptor(grpc.ServerInterceptor):
    """
    Validates bearer tokens on every incoming RPC.
    Returns UNAUTHENTICATED if token is missing or invalid.
    """

    def __init__(self, valid_tokens: set[str]):
        self._valid_tokens = valid_tokens

    def intercept_service(self, continuation, handler_call_details):
        # Extract metadata from incoming call
        metadata = dict(handler_call_details.invocation_metadata)
        auth_header = metadata.get("authorization", "")

        if not auth_header.startswith("Bearer "):
            # Return an abort handler; the actual RPC method is never called
            def abort(request, context):
                context.abort(grpc.StatusCode.UNAUTHENTICATED, "Missing bearer token")
            return grpc.unary_unary_rpc_method_handler(abort)

        token = auth_header[len("Bearer "):]
        if token not in self._valid_tokens:
            def abort(request, context):
                context.abort(grpc.StatusCode.UNAUTHENTICATED, "Invalid token")
            return grpc.unary_unary_rpc_method_handler(abort)

        # Token is valid; let the actual handler proceed
        return continuation(handler_call_details)


# =============================================================================
# PART 7 — gRPC STATUS CODES QUICK REFERENCE
# =============================================================================
# These are NOT HTTP codes. Map them to HTTP only at the gateway layer.
# =============================================================================

GRPC_STATUS_CODES = {
    "OK (0)": "Success",
    "CANCELLED (1)": "Client cancelled the call",
    "UNKNOWN (2)": "Unspecified error — avoid using this; pick a specific code",
    "INVALID_ARGUMENT (3)": "Client sent bad data; fix the request",
    "DEADLINE_EXCEEDED (4)": "Deadline expired before operation completed",
    "NOT_FOUND (5)": "Requested resource doesn't exist",
    "ALREADY_EXISTS (6)": "Resource already exists",
    "PERMISSION_DENIED (7)": "Caller lacks permission (authenticated but not authorized)",
    "RESOURCE_EXHAUSTED (8)": "Rate limited or quota exceeded",
    "FAILED_PRECONDITION (9)": "System not in required state (e.g., deleting non-empty bucket)",
    "ABORTED (10)": "Concurrency conflict (e.g., optimistic lock failure); retry transaction",
    "OUT_OF_RANGE (11)": "Value outside valid range (e.g., reading past end of file)",
    "UNIMPLEMENTED (12)": "Method not implemented or not supported",
    "INTERNAL (13)": "Serious internal error; likely a bug in the server",
    "UNAVAILABLE (14)": "Service unavailable; retry with backoff",
    "DATA_LOSS (15)": "Unrecoverable data loss or corruption",
    "UNAUTHENTICATED (16)": "No valid authentication credentials supplied",
}

# HTTP ↔ gRPC mapping (for grpc-gateway / REST transcoding layer only)
GRPC_TO_HTTP_STATUS = {
    "OK": 200,
    "CANCELLED": 499,           # Nginx/GCP convention for client cancellation
    "INVALID_ARGUMENT": 400,
    "DEADLINE_EXCEEDED": 504,   # Gateway timeout
    "NOT_FOUND": 404,
    "ALREADY_EXISTS": 409,
    "PERMISSION_DENIED": 403,
    "RESOURCE_EXHAUSTED": 429,
    "UNAUTHENTICATED": 401,
    "INTERNAL": 500,
    "UNAVAILABLE": 503,
    "UNIMPLEMENTED": 501,
}


# =============================================================================
# PART 8 — gRPC REFLECTION (service discovery)
# =============================================================================
# Reflection lets tools like grpcurl query your service without the .proto file.
# Enable in dev; often disabled in production for security.
# =============================================================================

CMD_GRPCURL_LIST = "grpcurl -plaintext localhost:50051 list"
CMD_GRPCURL_DESCRIBE = "grpcurl -plaintext localhost:50051 describe order.v2.OrderService"
CMD_GRPCURL_CALL = (
    "grpcurl -plaintext -d '{\"customer_id\": 42}' "
    "localhost:50051 order.v2.OrderService/CreateOrder"
)


def add_reflection_to_server(server: grpc.Server, service_names: list[str]) -> None:
    """
    Enable gRPC reflection on the given server.
    Requires: pip install grpcio-reflection
    """
    from grpc_reflection.v1alpha import reflection  # type: ignore[import]

    # SERVICE_NAME is generated by protoc into the pb2 module
    reflection.enable_server_reflection(service_names, server)
    logger.info("gRPC reflection enabled for %d services", len(service_names))


# =============================================================================
# PART 9 — gRPC HEALTH CHECKING PROTOCOL
# =============================================================================
# Standard protocol (grpc.health.v1) used by Kubernetes, Consul, Istio.
# Load balancers query /grpc.health.v1.Health/Check before routing traffic.
# =============================================================================

def add_health_checking(server: grpc.Server) -> None:
    """
    Add the standard gRPC health checking service.
    Requires: pip install grpcio-health-checking
    """
    from grpc_health.v1 import health, health_pb2, health_pb2_grpc  # type: ignore[import]

    health_servicer = health.HealthServicer(
        # experimental_non_blocking=True reduces latency for health checks
        experimental_non_blocking=True,
    )

    # Register each service with SERVING status
    health_servicer.set("", health_pb2.HealthCheckResponse.SERVING)  # overall
    health_servicer.set(
        "order.v2.OrderService",
        health_pb2.HealthCheckResponse.SERVING,
    )

    health_pb2_grpc.add_HealthServicer_to_server(health_servicer, server)
    logger.info("gRPC health checking service registered")

    # Check health with grpcurl:
    # grpcurl -plaintext localhost:50051 grpc.health.v1.Health/Check


# =============================================================================
# PART 10 — ASYNC gRPC (grpc.aio)
# =============================================================================
# For high-concurrency servers, use the async API instead of thread pools.
# Python 3.6+ asyncio; runs each RPC in a coroutine instead of a thread.
# =============================================================================

import asyncio


class AsyncOrderServiceServicer:
    """
    Async servicer — inherits from the grpc.aio generated base.
    All methods are coroutines (async def).
    """

    async def CreateOrder(self, request, context: grpc.aio.ServicerContext):
        """Async unary RPC handler."""
        # Await DB writes without blocking the event loop
        await asyncio.sleep(0)  # Placeholder for actual async DB call
        return {"order_id": "ORD-ASYNC-001", "status": 1}

    async def WatchOrderStatus(self, request, context: grpc.aio.ServicerContext):
        """Async server-streaming RPC. Use 'yield' to send each response."""
        for status in ["PENDING", "CONFIRMED", "DELIVERED"]:
            if context.cancelled():
                return
            yield {"status": status}
            await asyncio.sleep(1)  # Non-blocking sleep


async def serve_async(port: int = 50051) -> None:
    """Start the async gRPC server."""
    server = grpc.aio.server(
        options=[("grpc.max_receive_message_length", 16 * 1024 * 1024)]
    )
    # order_service_pb2_grpc.add_OrderServiceServicer_to_server(AsyncOrderServiceServicer(), server)
    server.add_insecure_port(f"[::]:{port}")
    await server.start()
    logger.info("Async gRPC server listening on port %d", port)
    await server.wait_for_termination()


# =============================================================================
# PART 11 — WHEN gRPC BEATS REST (and when it doesn't)
# =============================================================================

GRPC_WINS_WHEN = [
    "Internal service-to-service calls where you control both sides",
    "You need bidirectional streaming (chat, telemetry, live tracking)",
    "Binary payloads where JSON overhead is unacceptable (sensor data)",
    "Strict schema enforcement is needed across polyglot teams",
    "You generate typed clients for multiple languages from one .proto",
    "Multiplexing many concurrent RPC streams over a single connection",
]

REST_WINS_WHEN = [
    "Public APIs that third-party clients must integrate without SDK",
    "Browser-native clients (gRPC requires grpc-web or HTTP/JSON bridge)",
    "Simple CRUD with no streaming requirements",
    "Teams unfamiliar with protobuf toolchain",
    "CDN caching is critical (HTTP/2 gRPC responses are not CDN-cacheable)",
    "Debugging with curl, Postman, browser DevTools",
]


# =============================================================================
# DEMO BLOCK
# =============================================================================
if __name__ == "__main__":
    print("gRPC / Protobuf reference. Run serve() to start the server.")
    print(f"\nprotoc command:\n  {CMD_PROTOC}")
    print(f"\ngrpcurl inspect:\n  {CMD_GRPCURL_LIST}")
    print(f"\ngrpcurl call:\n  {CMD_GRPCURL_CALL}")

    # Show status code table
    print("\ngRPC Status Codes:")
    for code, description in GRPC_STATUS_CODES.items():
        print(f"  {code:<30} {description}")
