# ============================================================
# L02: Prometheus and Metrics
# ============================================================
# WHAT: Prometheus data model, metric types (Counter/Gauge/Histogram/
#       Summary), Python prometheus_client usage, PromQL queries,
#       label cardinality rules, and production metrics setup for
#       a FastAPI service.
# WHY:  Metrics are the cheapest observability signal — cheap to
#       collect, cheap to store, cheap to query. Prometheus is the
#       de-facto standard for cloud-native metrics. PromQL lets you
#       ask "what is my P99 latency right now?" in one line.
# LEVEL: Advanced
# ============================================================
"""
CONCEPT OVERVIEW:
    Prometheus uses a PULL model: it periodically scrapes a /metrics
    HTTP endpoint on each monitored service. This is different from
    StatsD/Datadog which use a PUSH model (service pushes to collector).

    Pull advantages:
      - Prometheus knows if a service is down (failed scrape = alert)
      - Services don't need to know Prometheus address
      - Easy to test: curl /metrics locally
    Pull disadvantages:
      - Short-lived jobs may complete before scrape (use Pushgateway)
      - Requires network access from Prometheus to each service

    Data model: metric_name{label1="val1", label2="val2"} value timestamp
    One unique label combination = one time series.
    Prometheus stores all time series in a TSDB (Time Series Database)
    on local disk using efficient column-oriented compression.

PRODUCTION USE CASE:
    FastAPI service with automatic instrumentation:
      - prometheus-fastapi-instrumentator auto-adds:
        http_requests_total, http_request_duration_seconds
      - Add custom metrics for: DB pool, cache hit rate, queue depth,
        business metrics (payments_total, orders_by_status)
      - Recording rules precompute expensive aggregations
      - Dashboards in Grafana query Prometheus via PromQL

COMMON MISTAKES:
    1. Using Summary instead of Histogram — Summary computes quantiles
       client-side and cannot be aggregated across instances. If you
       have 3 replicas, you CANNOT compute fleet-wide P99 from Summaries.
       Always use Histogram in production.
    2. High-cardinality labels — labeling with user_id, URL with IDs,
       session_id. Each unique value = one time series. At 1M users:
       1M time series × 3KB = 3GB just for one metric.
    3. Forgetting to normalize URL labels — /users/123 and /users/456
       must both map to /users/{id} or you get per-user time series.
    4. Using .inc() on a Gauge instead of .set() — Gauges should
       represent current state, not increments.
    5. Not using recording rules for expensive queries — histogram_quantile
       over 1M series computed in Grafana on every dashboard load is slow.
"""

import time
import random
import threading
from contextlib import contextmanager
from typing import Optional, Callable
from dataclasses import dataclass
from enum import Enum

# In production, install: pip install prometheus-client
# from prometheus_client import (
#     Counter, Gauge, Histogram, Summary,
#     CollectorRegistry, generate_latest, CONTENT_TYPE_LATEST,
#     start_http_server, push_to_gateway
# )


# ============================================================
# SECTION 1: PROMETHEUS DATA MODEL
# ============================================================
# Prometheus time series format:
#
# metric_name{label1="val1", label2="val2"} value [timestamp]
#
# Examples:
#   http_requests_total{method="POST",endpoint="/checkout",status_code="200"} 1847
#   http_request_duration_seconds_bucket{endpoint="/checkout",le="0.1"} 1204
#   http_request_duration_seconds_bucket{endpoint="/checkout",le="0.5"} 1799
#   http_request_duration_seconds_bucket{endpoint="/checkout",le="+Inf"} 1847
#   db_pool_connections_active{pool="primary"} 12
#
# Naming conventions:
#   - Use underscores (not dots or dashes)
#   - Append unit: _seconds, _bytes, _total, _ratio
#   - _total suffix: REQUIRED for Counters
#   - _bucket, _count, _sum: auto-generated by Histogram
#   - Base unit: seconds (not milliseconds), bytes (not megabytes)

@dataclass
class PrometheusMetricSpec:
    """Documents a metric's purpose, labels, and usage."""
    name: str
    metric_type: str        # counter | gauge | histogram | summary
    description: str
    labels: list[str]
    unit: str
    example_promql: str


# ============================================================
# SECTION 2: COUNTER
# ============================================================
# COUNTER: monotonically increasing value. NEVER resets (except
# process restart, which Prometheus handles with reset detection).
#
# Use for: total requests, total errors, total bytes sent,
#          total jobs processed, total retries
#
# DO NOT use for: current queue length, memory usage
# (those go up AND down → use Gauge)
#
# Key insight: counters are useless raw. Use rate() in PromQL.
#   raw counter = 1,847,392 requests (meaningless without timeframe)
#   rate(requests_total[5m]) = 47.3 requests/second (actionable)

class SimulatedCounter:
    """
    Simulates prometheus_client Counter behavior.
    In production:
        requests_total = Counter(
            'http_requests_total',
            'Total HTTP requests',
            ['method', 'endpoint', 'status_code']
        )
        requests_total.labels(method='POST', endpoint='/checkout', status_code='200').inc()
    """

    def __init__(self, name: str, description: str, labelnames: list[str]):
        self.name = name
        self.description = description
        self.labelnames = labelnames
        self._values: dict[tuple, float] = {}

    def labels(self, **kwargs) -> "SimulatedCounter._LabeledCounter":
        """Get a labeled version of this counter."""
        key = tuple(kwargs.get(l, "") for l in self.labelnames)
        return self._LabeledCounter(self, key)

    def _inc(self, label_key: tuple, amount: float = 1.0):
        """Increment counter (called by labeled counter)."""
        if amount < 0:
            raise ValueError("Counter cannot be decremented")
        self._values[label_key] = self._values.get(label_key, 0.0) + amount

    def get_value(self, **kwargs) -> float:
        key = tuple(kwargs.get(l, "") for l in self.labelnames)
        return self._values.get(key, 0.0)

    class _LabeledCounter:
        def __init__(self, parent: "SimulatedCounter", key: tuple):
            self._parent = parent
            self._key = key

        def inc(self, amount: float = 1.0):
            self._parent._inc(self._key, amount)


# ============================================================
# SECTION 3: GAUGE
# ============================================================
# GAUGE: current value that can go up or down.
#
# Use for: active connections, queue depth, memory used,
#          cache size, temperature, in-flight requests
#
# Methods: .set(n), .inc(n), .dec(n), .set_to_current_time()
#
# Gauge trap: if process restarts, gauge resets to 0 then increases.
# Prometheus handles this fine for current-state metrics.
# But if you're using a Gauge as a "running total" — use a Counter instead.

class SimulatedGauge:
    """
    Simulates prometheus_client Gauge.
    In production:
        active_connections = Gauge(
            'db_pool_connections_active',
            'Active database connections',
            ['pool_name']
        )
        active_connections.labels(pool_name='primary').set(12)
        active_connections.labels(pool_name='primary').inc()
        active_connections.labels(pool_name='primary').dec()
    """

    def __init__(self, name: str, description: str, labelnames: list[str]):
        self.name = name
        self.description = description
        self.labelnames = labelnames
        self._values: dict[tuple, float] = {}

    def labels(self, **kwargs) -> "SimulatedGauge._LabeledGauge":
        key = tuple(kwargs.get(l, "") for l in self.labelnames)
        return self._LabeledGauge(self, key)

    class _LabeledGauge:
        def __init__(self, parent: "SimulatedGauge", key: tuple):
            self._parent = parent
            self._key = key

        def set(self, value: float):
            """Set to an absolute value — use for polling current state."""
            self._parent._values[self._key] = value

        def inc(self, amount: float = 1.0):
            """Increment — use for tracking active requests."""
            current = self._parent._values.get(self._key, 0.0)
            self._parent._values[self._key] = current + amount

        def dec(self, amount: float = 1.0):
            current = self._parent._values.get(self._key, 0.0)
            self._parent._values[self._key] = current - amount

        @contextmanager
        def track_inprogress(self):
            """
            Context manager to track in-flight operations.
            Increments on enter, decrements on exit (even on exception).
            In production: use prometheus_client's track_inprogress().
            """
            self.inc()
            try:
                yield
            finally:
                self.dec()


# ============================================================
# SECTION 4: HISTOGRAM
# ============================================================
# HISTOGRAM: measures distribution of observed values using pre-defined
# "buckets". Each observation is counted in all buckets with le >= value.
#
# Auto-generates 3 time series per label combination:
#   metric_bucket{le="0.1"} = count of observations <= 0.1s
#   metric_count              = total observations
#   metric_sum                = sum of all observations
#
# Use for: request duration, response size, DB query time, batch size
#
# Bucket selection: cover the full realistic range.
# Default buckets: .005, .01, .025, .05, .1, .25, .5, 1, 2.5, 5, 10
# For a web API targeting P99 < 200ms, use custom buckets:
#   .001, .005, .01, .025, .05, .1, .25, .5, 1, 2.5
# This gives better resolution around the SLO threshold (0.1s = 100ms)
#
# PromQL to compute P99:
#   histogram_quantile(0.99, rate(http_request_duration_seconds_bucket[5m]))
#
# This works across multiple instances! Unlike Summary.
# Prometheus aggregates all the _bucket series before computing quantile.

class SimulatedHistogram:
    """
    Simulates prometheus_client Histogram.
    In production:
        duration_histogram = Histogram(
            'http_request_duration_seconds',
            'Request duration in seconds',
            ['method', 'endpoint'],
            buckets=[.001, .005, .01, .025, .05, .1, .25, .5, 1, 2.5]
        )
        with duration_histogram.labels(method='POST', endpoint='/checkout').time():
            process_request()
    """

    DEFAULT_BUCKETS = [.005, .01, .025, .05, .1, .25, .5, 1.0, 2.5, 5.0, float('inf')]

    def __init__(
        self,
        name: str,
        description: str,
        labelnames: list[str],
        buckets: Optional[list[float]] = None,
    ):
        self.name = name
        self.description = description
        self.labelnames = labelnames
        # Always ensure +Inf bucket exists (catches all observations)
        self.buckets = sorted(set((buckets or self.DEFAULT_BUCKETS) + [float('inf')]))
        # bucket_counts[(label_key, le)] = count
        self._bucket_counts: dict[tuple, int] = {}
        self._sum: dict[tuple, float] = {}
        self._count: dict[tuple, int] = {}

    def labels(self, **kwargs) -> "SimulatedHistogram._LabeledHistogram":
        key = tuple(kwargs.get(l, "") for l in self.labelnames)
        return self._LabeledHistogram(self, key)

    def _observe(self, label_key: tuple, value: float):
        """
        Record one observation. Increments all buckets where le >= value.
        This is O(buckets) per observation — typically 10-15 buckets.
        """
        for bucket in self.buckets:
            bkey = (label_key, bucket)
            if value <= bucket:
                self._bucket_counts[bkey] = self._bucket_counts.get(bkey, 0) + 1

        self._sum[label_key] = self._sum.get(label_key, 0.0) + value
        self._count[label_key] = self._count.get(label_key, 0) + 1

    def get_bucket_data(self, **kwargs) -> list[tuple[float, int]]:
        """Returns (bucket_le, cumulative_count) pairs for PromQL simulation."""
        key = tuple(kwargs.get(l, "") for l in self.labelnames)
        return [
            (b, self._bucket_counts.get((key, b), 0))
            for b in self.buckets
        ]

    class _LabeledHistogram:
        def __init__(self, parent: "SimulatedHistogram", key: tuple):
            self._parent = parent
            self._key = key

        def observe(self, value: float):
            """Record a single observation (e.g., request duration in seconds)."""
            self._parent._observe(self._key, value)

        @contextmanager
        def time(self):
            """
            Context manager: automatically observes elapsed time in seconds.
            Usage:
                with duration.labels(method='GET', endpoint='/health').time():
                    result = do_work()
            """
            start = time.perf_counter()
            try:
                yield
            finally:
                elapsed = time.perf_counter() - start
                self.observe(elapsed)

    def compute_quantile(self, q: float, **kwargs) -> float:
        """
        Compute approximate quantile from histogram buckets.
        This is what histogram_quantile() does in PromQL.
        Approximation accuracy depends on bucket resolution.
        """
        key = tuple(kwargs.get(l, "") for l in self.labelnames)
        total = self._count.get(key, 0)
        if total == 0:
            return 0.0

        target_count = q * total

        # Find the bucket where cumulative count crosses target
        prev_count = 0
        prev_bound = 0.0

        for bucket in self.buckets:
            bkey = (key, bucket)
            count = self._bucket_counts.get(bkey, 0)

            if count >= target_count:
                # Interpolate within this bucket
                if bucket == float('inf'):
                    return prev_bound
                count_in_bucket = count - prev_count
                if count_in_bucket == 0:
                    return prev_bound
                fraction = (target_count - prev_count) / count_in_bucket
                return prev_bound + fraction * (bucket - prev_bound)

            prev_count = count
            prev_bound = bucket

        return self.buckets[-2] if len(self.buckets) > 1 else 0.0


# ============================================================
# SECTION 5: WHY NOT SUMMARY
# ============================================================
# Summary: computes quantiles on the CLIENT side (in the application).
#
# Problem: if you have 3 replicas and each computes P99 independently,
# you CANNOT combine them into a fleet-wide P99.
#   Replica 1 P99 = 180ms
#   Replica 2 P99 = 220ms
#   Replica 3 P99 = 195ms
#   Fleet P99 = ??? (you don't know — it requires all data)
#
# With Histogram:
#   All three replicas expose bucket counts
#   PromQL sums the buckets: sum(rate(..._bucket[5m])) by (le)
#   histogram_quantile(0.99, ...) computes accurate fleet-wide P99
#
# Summary use case: none in modern systems. Use Histogram always.
# Exception: if you need exact (not approximate) quantiles and only
# have 1 instance — but this is rare.

SUMMARY_HISTOGRAM_COMPARISON = {
    "Histogram": {
        "quantile_accuracy": "Approximate (depends on bucket resolution)",
        "aggregatable": "YES — can sum across replicas",
        "memory": "O(buckets) per label combination",
        "use_when": "Always — the standard choice",
    },
    "Summary": {
        "quantile_accuracy": "Exact (computed from all observations)",
        "aggregatable": "NO — per-instance only",
        "memory": "O(observations in sliding window)",
        "use_when": "Almost never — prefer Histogram",
    },
}


# ============================================================
# SECTION 6: PRODUCTION METRICS FOR A FastAPI SERVICE
# ============================================================

class ProductionMetrics:
    """
    Complete metrics setup for a production FastAPI service.
    Demonstrates all metric types with correct usage patterns.

    In production (FastAPI + prometheus-fastapi-instrumentator):

        from prometheus_fastapi_instrumentator import Instrumentator

        app = FastAPI()

        # Auto-instruments: http_requests_total, http_request_duration_seconds
        Instrumentator().instrument(app).expose(app)

    Then add custom metrics below for business logic.
    """

    def __init__(self):
        # ---- HTTP metrics (auto-instrumented in production) ----
        self.requests_total = SimulatedCounter(
            "http_requests_total",
            "Total HTTP requests by method, endpoint, and status",
            ["method", "endpoint", "status_code"],
        )
        self.request_duration = SimulatedHistogram(
            "http_request_duration_seconds",
            "HTTP request duration in seconds",
            ["method", "endpoint"],
            # Custom buckets: fine resolution around SLO threshold (100ms)
            buckets=[.001, .005, .01, .025, .05, .1, .2, .5, 1.0, 2.5, 5.0],
        )
        self.active_requests = SimulatedGauge(
            "http_requests_active",
            "Currently processing HTTP requests",
            ["endpoint"],
        )

        # ---- Database metrics ----
        self.db_pool_active = SimulatedGauge(
            "db_pool_connections_active",
            "Active connections currently checked out from pool",
            ["pool_name"],
        )
        self.db_pool_size = SimulatedGauge(
            "db_pool_connections_total",
            "Total connections in pool (active + idle)",
            ["pool_name"],
        )
        self.db_query_duration = SimulatedHistogram(
            "db_query_duration_seconds",
            "Database query execution time",
            ["operation", "table"],  # operation: select|insert|update|delete
            buckets=[.001, .005, .01, .025, .05, .1, .5, 1.0, 5.0],
        )

        # ---- Cache metrics ----
        self.cache_operations = SimulatedCounter(
            "cache_operations_total",
            "Cache operations by result (hit or miss)",
            ["cache_name", "result"],  # result: hit | miss
        )

        # ---- Queue metrics ----
        self.queue_depth = SimulatedGauge(
            "message_queue_depth",
            "Number of messages waiting in queue",
            ["queue_name"],
        )
        self.queue_processed = SimulatedCounter(
            "queue_messages_processed_total",
            "Messages processed from queue",
            ["queue_name", "status"],  # status: success | failure
        )

        # ---- Business metrics ----
        self.orders_total = SimulatedCounter(
            "business_orders_total",
            "Orders placed by status",
            ["status", "payment_method"],  # status: success|failed|refunded
        )
        self.revenue_total = SimulatedCounter(
            "business_revenue_cents_total",
            "Revenue collected in cents",
            ["currency", "payment_method"],
        )

    def record_request(
        self,
        method: str,
        endpoint: str,
        status_code: int,
        duration_seconds: float,
    ):
        """Record metrics for one completed HTTP request."""
        # Normalize endpoint: /users/123 → /users/{id}
        # Real: use regex patterns or route matching
        normalized_endpoint = self._normalize_endpoint(endpoint)

        self.requests_total.labels(
            method=method,
            endpoint=normalized_endpoint,
            status_code=str(status_code),
        ).inc()

        self.request_duration.labels(
            method=method,
            endpoint=normalized_endpoint,
        ).observe(duration_seconds)

    def record_db_query(self, operation: str, table: str, duration_seconds: float):
        """Record metrics for one database query."""
        self.db_query_duration.labels(
            operation=operation,
            table=table,
        ).observe(duration_seconds)

    def record_cache_operation(self, cache_name: str, hit: bool):
        """Record cache hit or miss."""
        result = "hit" if hit else "miss"
        self.cache_operations.labels(
            cache_name=cache_name,
            result=result,
        ).inc()

    def record_order(
        self,
        status: str,
        payment_method: str,
        amount_cents: int,
        currency: str = "USD",
    ):
        """Record business metrics for an order."""
        self.orders_total.labels(
            status=status,
            payment_method=payment_method,
        ).inc()

        if status == "success":
            self.revenue_total.labels(
                currency=currency,
                payment_method=payment_method,
            ).inc(amount_cents)

    def _normalize_endpoint(self, path: str) -> str:
        """
        Replace dynamic path segments with placeholders.
        CRITICAL: prevents high-cardinality time series.
        /users/123 → /users/{id}
        /orders/abc-def → /orders/{order_id}
        """
        import re
        # Replace UUIDs: 8-4-4-4-12 hex pattern
        path = re.sub(
            r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}',
            '{uuid}', path
        )
        # Replace numeric IDs
        path = re.sub(r'/\d+', '/{id}', path)
        return path


# ============================================================
# SECTION 7: PROMQL REFERENCE
# ============================================================
# PromQL is Prometheus's query language. Used in Grafana dashboards
# and alert rules. Understanding PromQL is essential for production.

PROMQL_REFERENCE = {
    "rate": {
        "syntax": "rate(counter_metric[5m])",
        "description": "Per-second average rate of counter increase over 5m window",
        "example": "rate(http_requests_total[5m])",
        "result": "47.3 (requests per second, averaged over 5 minutes)",
        "note": "Use rate() not irate() for alerting — rate() is smoother. "
                "irate() uses only last 2 samples — too spiky for alerts.",
    },
    "irate": {
        "syntax": "irate(counter_metric[5m])",
        "description": "Instant rate (uses last 2 data points in window)",
        "example": "irate(http_requests_total[5m])",
        "note": "Better for dashboards where you want to see sudden spikes. "
                "Do NOT use for alerts (too noisy).",
    },
    "sum_by": {
        "syntax": "sum by (label) (metric)",
        "example": "sum by (endpoint) (rate(http_requests_total[5m]))",
        "result": "QPS broken down per endpoint (summed across all method/status_code)",
    },
    "histogram_quantile": {
        "syntax": "histogram_quantile(quantile, rate(histogram_bucket[window]))",
        "example": "histogram_quantile(0.99, sum by (le, endpoint) (rate(http_request_duration_seconds_bucket[5m])))",
        "result": "P99 latency per endpoint across all instances",
        "note": "Always sum by (le, ...) before histogram_quantile. "
                "The 'le' label MUST be preserved for the function to work.",
    },
    "increase": {
        "syntax": "increase(counter_metric[1h])",
        "description": "Total increase in counter over time window",
        "example": "increase(http_requests_total{status_code='500'}[1h])",
        "result": "Total 500 errors in the last hour (as a whole number)",
        "note": "Useful for 'how many X in the last hour?' queries.",
    },
    "error_rate": {
        "syntax": "sum(rate(errors[5m])) / sum(rate(total[5m]))",
        "example": (
            "sum(rate(http_requests_total{status_code=~'5..'}[5m]))\n"
            "  /\n"
            "sum(rate(http_requests_total[5m]))"
        ),
        "result": "0.0031 = 0.31% error rate",
    },
    "cache_hit_rate": {
        "syntax": "rate(cache_hit) / (rate(cache_hit) + rate(cache_miss))",
        "example": (
            "sum(rate(cache_operations_total{result='hit'}[5m]))\n"
            "  /\n"
            "sum(rate(cache_operations_total[5m]))"
        ),
        "result": "0.92 = 92% cache hit rate",
    },
    "db_pool_utilization": {
        "example": "db_pool_connections_active / db_pool_connections_total",
        "result": "0.65 = 65% pool utilization",
        "alert": "> 0.8 for > 5 minutes → pool exhaustion risk",
    },
}


# ============================================================
# SECTION 8: LABEL CARDINALITY — DETAILED RULES
# ============================================================

class LabelCardinalityValidator:
    """
    Validates that metric labels won't cause cardinality explosion.
    In production: enforce this at code review time.
    """

    # Maximum acceptable cardinality per metric family
    MAX_SERIES_PER_METRIC = 10_000

    # Labels that are ALWAYS forbidden (unbounded)
    FORBIDDEN_LABEL_PATTERNS = [
        "user_id", "customer_id", "account_id",  # millions of users
        "request_id", "trace_id", "session_id",  # one per request
        "ip_address", "ip",                       # millions of IPs
        "timestamp", "date", "time",              # infinite time values
        "url", "path",                            # unparameterized paths
        "query",                                  # query string values
        "email",                                  # PII + unbounded
    ]

    # Labels that are OK (bounded, low cardinality)
    RECOMMENDED_LABELS = {
        "http": ["method", "endpoint", "status_code"],
        # method: GET/POST/PUT/DELETE/PATCH = 5 values
        # endpoint: normalized paths, typically < 50
        # status_code: 200/201/400/401/404/422/429/500/503 ≈ 15 values
        # → max series: 5 × 50 × 15 = 3,750 ✓

        "database": ["operation", "table", "db_name"],
        # operation: select/insert/update/delete = 4
        # table: typically < 30 tables
        # → max series: 4 × 30 = 120 ✓

        "cache": ["cache_name", "result"],
        # cache_name: user_cache, product_cache etc = < 10
        # result: hit/miss = 2
        # → max series: 10 × 2 = 20 ✓

        "queue": ["queue_name", "status"],
        # queue_name: < 20 queues
        # status: success/failure = 2
        # → max series: 20 × 2 = 40 ✓
    }

    @classmethod
    def validate_labels(cls, metric_name: str, labels: list[str]) -> list[str]:
        """Returns list of warnings for problematic label choices."""
        warnings = []

        for label in labels:
            label_lower = label.lower()
            for forbidden in cls.FORBIDDEN_LABEL_PATTERNS:
                if forbidden in label_lower:
                    warnings.append(
                        f"DANGER: label '{label}' in metric '{metric_name}' "
                        f"matches forbidden pattern '{forbidden}'. "
                        f"This will create unbounded time series. "
                        f"Use logs or traces for per-entity debugging."
                    )
                    break

        return warnings


# ============================================================
# SECTION 9: RECORDING RULES
# ============================================================
# Recording rules precompute expensive PromQL expressions and store
# results as new metrics. Grafana then queries the precomputed metric
# instead of running the expensive computation on every dashboard load.
#
# Benefits:
#   - Dashboard load time: seconds → milliseconds
#   - Reduce Prometheus query load
#   - Complex multi-step calculations become queryable
#
# Rules are defined in YAML and loaded by Prometheus.

RECORDING_RULES_YAML = """
groups:
  - name: api_slo_rules
    interval: 30s  # evaluate every 30 seconds
    rules:

      # Precompute per-endpoint error rate
      # Raw query on every dashboard load: slow at scale
      # Precomputed: instant read of one time series
      - record: job:http_error_rate:rate5m
        expr: |
          sum by (endpoint) (
            rate(http_requests_total{status_code=~"5.."}[5m])
          )
          /
          sum by (endpoint) (
            rate(http_requests_total[5m])
          )

      # Precompute P99 latency per endpoint
      # histogram_quantile over many series is CPU-intensive
      - record: job:http_p99_latency:rate5m
        expr: |
          histogram_quantile(0.99,
            sum by (le, endpoint) (
              rate(http_request_duration_seconds_bucket[5m])
            )
          )

      # Precompute P50 latency (median)
      - record: job:http_p50_latency:rate5m
        expr: |
          histogram_quantile(0.50,
            sum by (le, endpoint) (
              rate(http_request_duration_seconds_bucket[5m])
            )
          )

      # Error budget burn rate (for SLO alerting — see L04)
      # target_error_rate = 1 - SLO = 0.001 for 99.9% SLO
      - record: job:error_budget_burn_rate:rate1h
        expr: |
          (
            sum(rate(http_requests_total{status_code=~"5.."}[1h]))
            /
            sum(rate(http_requests_total[1h]))
          ) / 0.001  # 0.001 = 1 - 0.999 (SLO target)

      # DB pool utilization ratio
      - record: job:db_pool_utilization:instant
        expr: |
          db_pool_connections_active / db_pool_connections_total
"""


# ============================================================
# SECTION 10: COMPLETE PRODUCTION METRICS DASHBOARD SPEC
# ============================================================

GRAFANA_DASHBOARD_PANELS = [
    {
        "title": "Request Rate (QPS)",
        "type": "graph",
        "promql": "sum by (endpoint) (rate(http_requests_total[5m]))",
        "unit": "req/s",
        "alert": None,  # Informational — alert on error rate instead
    },
    {
        "title": "Error Rate (%)",
        "type": "graph",
        "promql": (
            "sum(rate(http_requests_total{status_code=~'5..'}[5m]))"
            " / sum(rate(http_requests_total[5m])) * 100"
        ),
        "unit": "%",
        "alert": "Error rate > 1% for 2+ minutes → page on-call",
    },
    {
        "title": "Latency P50 / P95 / P99",
        "type": "graph",
        "promql": {
            "P50": "histogram_quantile(0.50, sum by(le)(rate(http_request_duration_seconds_bucket[5m])))",
            "P95": "histogram_quantile(0.95, sum by(le)(rate(http_request_duration_seconds_bucket[5m])))",
            "P99": "histogram_quantile(0.99, sum by(le)(rate(http_request_duration_seconds_bucket[5m])))",
        },
        "unit": "seconds",
        "alert": "P99 > 0.2s for 5+ minutes → investigate",
    },
    {
        "title": "DB Pool Utilization",
        "type": "gauge",
        "promql": "db_pool_connections_active / db_pool_connections_total * 100",
        "unit": "%",
        "thresholds": {"green": 0, "yellow": 70, "red": 85},
        "alert": "Pool > 85% for 5+ minutes → scale DB connections",
    },
    {
        "title": "Cache Hit Rate",
        "type": "stat",
        "promql": (
            "sum(rate(cache_operations_total{result='hit'}[5m]))"
            " / sum(rate(cache_operations_total[5m])) * 100"
        ),
        "unit": "%",
        "alert": "Hit rate < 70% → cache strategy review needed",
    },
    {
        "title": "Queue Depth",
        "type": "graph",
        "promql": "message_queue_depth",
        "unit": "messages",
        "alert": "Growing continuously for > 10min → consumer lag alert",
    },
    {
        "title": "Revenue (last hour)",
        "type": "stat",
        "promql": "increase(business_revenue_cents_total[1h]) / 100",
        "unit": "USD",
        "alert": None,  # Business metric — trend in Slack, not page
    },
]


# ============================================================
# DEMO: Simulate metrics collection and PromQL-like queries
# ============================================================

def run_demo():
    print("=" * 60)
    print("PROMETHEUS METRICS DEMO")
    print("=" * 60)

    metrics = ProductionMetrics()

    # Simulate traffic for 100 requests
    print("\nSimulating 100 HTTP requests...")
    endpoints = ["/api/checkout", "/api/products/{id}", "/api/users/{id}"]
    methods = ["GET", "POST"]
    for i in range(100):
        endpoint = random.choice(endpoints)
        method = "GET" if endpoint != "/api/checkout" else "POST"
        # Simulate latency: checkout is slower
        if endpoint == "/api/checkout":
            duration = random.gauss(0.35, 0.1)
        else:
            duration = random.gauss(0.05, 0.02)
        duration = max(0.001, duration)
        # Simulate 2% error rate
        status = 500 if random.random() < 0.02 else 200
        metrics.record_request(method, endpoint, status, duration)

    # Simulate cache operations (85% hit rate)
    print("Simulating 200 cache lookups...")
    for _ in range(200):
        hit = random.random() < 0.85
        metrics.record_cache_operation("product_cache", hit)
        metrics.cache_operations.labels(
            cache_name="product_cache",
            result="hit" if hit else "miss",
        ).inc()

    # Report P99 latency per endpoint
    print("\n--- P99 Latency by Endpoint ---")
    for endpoint in endpoints:
        normalized = metrics._normalize_endpoint(endpoint)
        p99 = metrics.request_duration.compute_quantile(
            0.99, method="GET", endpoint=normalized
        )
        print(f"  {normalized}: P99 = {p99*1000:.1f}ms")

    # Report cache hit rate
    total_hits = metrics.cache_operations.get_value(
        cache_name="product_cache", result="hit"
    )
    total_misses = metrics.cache_operations.get_value(
        cache_name="product_cache", result="miss"
    )
    total = total_hits + total_misses
    hit_rate = (total_hits / total * 100) if total > 0 else 0
    print(f"\n--- Cache Hit Rate ---")
    print(f"  product_cache: {hit_rate:.1f}% (target: > 90%)")

    # Cardinality validation demo
    print("\n--- Label Cardinality Validation ---")
    bad_labels = ["endpoint", "user_id", "status_code", "request_id"]
    warnings = LabelCardinalityValidator.validate_labels(
        "http_requests_total", bad_labels
    )
    for warning in warnings:
        print(f"  ⚠ {warning[:80]}...")


if __name__ == "__main__":
    run_demo()
