# ============================================================
# L14: Audio Fingerprinting Fundamentals — How Shazam "Hears" a Song
# ============================================================
# WHAT: How Shazam converts a noisy, few-seconds audio clip recorded from
#       a phone's microphone into a compact, ROBUST "fingerprint" that can
#       be matched against a reference database — even through background
#       noise, other people talking, and poor microphone quality.
# WHY: New case study: Shazam. This is a fundamentally different problem
#      from L11-L13's streaming/recommendation focus — it's a SIGNAL
#      PROCESSING and EXACT-MATCH-AT-SCALE problem, closer in spirit to
#      L05's linear-algebra/vector concepts than to typical CRUD system design.
# LEVEL: Foundation (of this case study)
# ============================================================

"""
CONCEPT OVERVIEW:
A SPECTROGRAM is a visual/mathematical representation of audio showing
FREQUENCY content over TIME (as opposed to a raw waveform, which shows
amplitude over time) — computed via the Short-Time Fourier Transform
(STFT): the audio is divided into small overlapping time windows, and a
Fourier Transform is applied to EACH window to extract which frequencies
are present during that specific slice of time. This time-frequency
representation is the foundation everything else in this lesson builds on.

THE KEY INSIGHT — CONSTELLATION MAPS: rather than trying to match the
ENTIRE spectrogram (which would be extremely sensitive to noise, volume
differences, and exact timing), Shazam's algorithm (published by Avery
Wang, Shazam's co-founder, in a widely-cited paper) identifies PEAKS —
the LOUDEST frequency at each moment, or more precisely, local maxima in
the spectrogram that stand out clearly above the surrounding
noise floor — plotting these peaks as points in time-frequency space
produces a sparse "constellation" pattern that is DRAMATICALLY more
ROBUST to background noise than the full spectrogram, because noise
tends to raise the overall noise floor roughly uniformly, while genuine
musical peaks remain identifiable as distinct local maxima above it.

HASHING PAIRS OF PEAKS, not individual peaks, is what makes fingerprint
MATCHING efficient and further noise-resistant: the algorithm pairs each
peak with several nearby peaks (an "anchor" point and a set of "target"
points within a defined time-frequency window), and computes a HASH from
each pair's (frequency of point 1, frequency of point 2, time difference
between them) — critically, this hash is TIME-TRANSLATION INVARIANT: it
doesn't matter WHEN in the song this pair of peaks occurred, only their
relative frequency/timing relationship — which is exactly what lets a
5-second clip recorded starting at a RANDOM point in a song still match
against a fingerprint database built from the full track.

ROBUSTNESS TO REAL-WORLD RECORDING CONDITIONS is the entire point of this
peak-pair-hashing approach: background chatter, other music, a phone's
low-quality microphone, and the fact that the clip could start at ANY
point in the song are all real conditions the fingerprinting scheme must
survive — by relying on sparse, locally-dominant peaks (unlikely to be
generated by unrelated background noise) and TIME-RELATIVE hashes
(insensitive to WHERE the query clip starts), the scheme tolerates a
remarkable amount of real-world degradation while remaining highly
DISCRIMINATIVE (avoiding false matches to unrelated songs).

PRODUCTION USE CASE:
A user holds their phone up in a noisy bar to identify a song playing
over background chatter and other ambient noise — Shazam's client
records a few seconds of audio, computes its spectrogram, extracts
constellation-map peaks (which the loud, clear music tends to produce
consistently, while random background chatter mostly does not produce
strong, consistent peaks at the SAME frequencies the music does), hashes
peak pairs, and sends these compact hashes (not the raw audio) to be
matched against a reference database — this lesson's L15 covers HOW that
matching happens efficiently across a catalog of tens of millions of songs.

COMMON MISTAKES:
- Attempting to match RAW AUDIO WAVEFORMS directly rather than extracting
  a fingerprint — raw waveform comparison is extremely sensitive to
  noise, volume, and exact timing alignment, making it impractical for
  real-world noisy recording conditions.
- Hashing individual peaks in isolation rather than PAIRS of peaks — a
  single peak's frequency alone is not distinctive enough (many songs
  share individual frequency peaks); it's the RELATIONSHIP between pairs
  of peaks (their relative frequencies and timing) that provides enough
  distinctiveness to reliably identify a specific song among millions.
- Using a hash scheme that depends on ABSOLUTE time position within the
  song — this would only work if the query clip started at EXACTLY the
  same point the reference fingerprint was indexed from, which is never
  true for a real-world clip recorded starting at an arbitrary moment.
"""

import math


# ------------------------------------------------------------------
# 1. A simplified spectrogram — frequency content over time windows
# ------------------------------------------------------------------
def simplified_spectrogram(signal_freqs_over_time: list[list[float]]) -> list[list[float]]:
    """A stand-in for real STFT output: each inner list represents the
    dominant frequencies present during one time window."""
    return signal_freqs_over_time


# ------------------------------------------------------------------
# 2. Extracting constellation-map peaks
# ------------------------------------------------------------------
def extract_peaks(spectrogram: list[list[float]]) -> list[tuple[int, float]]:
    """Returns (time_index, frequency) for the DOMINANT frequency in each
    time window — a drastically simplified stand-in for real peak-picking,
    which considers local maxima across BOTH time and frequency."""
    peaks = []
    for t, frequencies_present in enumerate(spectrogram):
        if frequencies_present:
            dominant_freq = max(frequencies_present)
            peaks.append((t, dominant_freq))
    return peaks


# ------------------------------------------------------------------
# 3. Hashing peak PAIRS — time-translation-invariant fingerprints
# ------------------------------------------------------------------
def hash_peak_pairs(peaks: list[tuple[int, float]], max_pair_distance: int = 3) -> list[dict]:
    hashes = []
    for i, (t1, f1) in enumerate(peaks):
        # Pair this "anchor" peak with nearby "target" peaks within a window
        for t2, f2 in peaks[i + 1: i + 1 + max_pair_distance]:
            time_delta = t2 - t1
            # The hash captures ONLY the relative relationship — NOT the
            # absolute time t1 — making it invariant to where in the
            # song this pair happens to occur
            fingerprint_hash = f"f1={f1:.0f}|f2={f2:.0f}|dt={time_delta}"
            hashes.append({"hash": fingerprint_hash, "anchor_time": t1})
    return hashes


def fingerprinting_demo():
    # A simplified spectrogram: each entry is the set of frequencies
    # detected at that time window (in a real system, derived via STFT)
    spectrogram = [
        [220, 440],       # t=0
        [440, 880],       # t=1
        [330],            # t=2 (background noise creates spurious low peak)
        [440, 660],       # t=3
        [880],            # t=4
    ]

    peaks = extract_peaks(spectrogram)
    print(f"Extracted constellation peaks (time, dominant_freq): {peaks}")

    hashes = hash_peak_pairs(peaks)
    print(f"\nGenerated {len(hashes)} peak-pair hashes (TIME-TRANSLATION INVARIANT):")
    for h in hashes:
        print(f"  {h['hash']}  (anchor at t={h['anchor_time']})")

    print("\n  -> If this exact pattern of peaks occurred starting at t=50")
    print("     instead of t=0 in a different recording, the resulting")
    print("     hashes would be IDENTICAL — only the recorded anchor_time")
    print("     differs, which is exactly what makes matching a clip that")
    print("     starts at a random point in a song possible (see L15).")


if __name__ == "__main__":
    fingerprinting_demo()

"""
PRODUCTION CONTEXT EXAMPLE:
Shazam correctly identifies a song from a 5-second clip recorded in a
crowded, noisy restaurant, despite background conversation, clinking
dishes, and a phone microphone of modest quality — this works because
the peak-extraction step is specifically robust to noise (background
chatter rarely produces strong, CONSISTENT frequency peaks the way
music does), and the pair-hashing step doesn't require knowing WHERE in
the original track this particular 5-second window came from — both
properties directly addressing the two hardest real-world constraints
audio fingerprinting has to survive.
"""
