// ============================================================
// L04: Database Access and gRPC in Go
// ============================================================
// WHAT: pgxpool connection pool, sqlc type-safe queries,
//       database transactions, proto3 service definitions,
//       gRPC server/client setup, and unary interceptors.
// WHY:  Go's database/sql is the lowest-level interface; pgx/v5
//       is the idiomatic PostgreSQL driver. gRPC over HTTP/2
//       gives you strongly-typed, generated client/server stubs,
//       streaming, and efficient binary serialisation — all
//       without hand-writing JSON marshalling.
// LEVEL: Intermediate
// ============================================================
/* CONCEPT OVERVIEW:
   database/sql is the standard library interface. Any driver
   (pgx, lib/pq) registers with it. pgx/v5 also provides its
   own native API (pgxpool) that bypasses database/sql for
   better performance and PostgreSQL-specific features.

   pgxpool is a thread-safe connection pool. Connections are
   borrowed for a query and returned automatically. Pool sizing:
   MaxConns should be set so that (instances × MaxConns) does
   not exceed PostgreSQL's max_connections (default 100).
   A rule of thumb: MaxConns = max_connections / app_instances.

   sqlc generates type-safe Go code from .sql query files.
   You write SQL; sqlc produces a Go function with the exact
   input/output types. No ORM magic, no reflection at runtime,
   compile-time errors for schema mismatches.

   Transactions: begin → deferred rollback → do work → commit.
   The deferred rollback is a no-op if Commit succeeds; it only
   fires on early return or panic, guaranteeing no partial writes.

   gRPC: define messages and services in .proto files. Run
   protoc to generate Go interfaces. Implement the interface
   on a struct. Register with grpc.NewServer. Interceptors
   wrap every call (logging, auth, recovery) — equivalent to
   HTTP middleware.

   PRODUCTION USE CASE:
   Internal microservices communicate via gRPC (binary, fast,
   contract-first). Public-facing API uses a gRPC-Gateway to
   translate REST/JSON → gRPC. The user-service uses pgxpool
   for DB access, sqlc for type-safe queries, and a transaction
   for atomic fund transfers.

   COMMON MISTAKES:
   1. Forgetting rows.Close() — every open rows object holds a
      connection from the pool; if you don't close it the pool
      drains and new queries block forever.
   2. Not using context with timeout — a runaway DB query or
      unresponsive gRPC peer blocks the goroutine indefinitely.
      Always derive a context with deadline from the incoming ctx.
   3. Changing proto field numbers — field numbers are permanent.
      Changing them breaks all existing serialised data and every
      deployed client. Add new fields with new numbers; never
      reuse or change existing ones.
   4. Ignoring tx.Rollback() error — deferred rollback after a
      successful commit returns ErrTxDone, which is harmless and
      expected; don't log it as an error.
   5. MaxConns too high — each PostgreSQL connection uses ~5 MB
      of RAM. 100 app pods × 50 MaxConns = 5 000 connections =
      25 GB RAM on the DB server. Size carefully. */

package main

import (
	"context"
	"errors"
	"fmt"
	"log"
	"log/slog"
	"net"
	"os"
	"time"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgxpool"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"

	// Generated by protoc-gen-go and protoc-gen-go-grpc.
	// In a real project: google.golang.org/protobuf/proto
	// pb "github.com/yourorg/userservice/gen/pb"
)

// ===========================================================================
// DOMAIN MODELS
// These mirror the proto3 message definitions. In production they would
// be in the generated pb package; defined here for self-containedness.
// ===========================================================================

// User is the core domain entity. Maps to both the DB row and the proto
// message — in a real project these are separate structs with a mapping
// function to avoid coupling DB schema to the wire format.
type User struct {
	ID    int64
	Name  string
	Email string
}

// CreateUserParams is what sqlc generates from:
//
//	-- name: CreateUser :one
//	INSERT INTO users (name, email) VALUES ($1, $2) RETURNING id, name, email;
type CreateUserParams struct {
	Name  string
	Email string
}

// TransferParams holds the data needed for an atomic fund transfer.
type TransferParams struct {
	FromAccountID int64
	ToAccountID   int64
	Amount        int64 // store money as integer cents — never float
}

// ===========================================================================
// DATABASE CONNECTION POOL (pgx/v5)
// pgxpool is safe for concurrent use from multiple goroutines.
// Connections are checked out for a query and returned to the pool
// automatically when the query completes.
// ===========================================================================

// NewPool creates a pgxpool with production-ready settings.
// dsn format: "postgres://user:pass@host:5432/dbname?sslmode=require"
func NewPool(ctx context.Context, dsn string) (*pgxpool.Pool, error) {
	cfg, err := pgxpool.ParseConfig(dsn)
	if err != nil {
		return nil, fmt.Errorf("parse dsn: %w", err)
	}

	// MaxConns: rule of thumb = postgres max_connections / num_instances.
	// Overloading the DB with too many connections is worse than too few;
	// pgxpool queues connection requests rather than failing immediately.
	cfg.MaxConns = 25

	// MinConns: keep 5 connections warm. Avoids the latency spike of
	// creating a fresh TCP connection on the first query after idle.
	cfg.MinConns = 5

	// Recycle connections after 1 hour regardless of activity.
	// Prevents issues with PostgreSQL-side idle connection timeouts.
	cfg.MaxConnLifetime = time.Hour

	// Return idle connections to the OS after 30 minutes.
	// Reduces PostgreSQL memory pressure during off-peak hours.
	cfg.MaxConnIdleTime = 30 * time.Minute

	// HealthCheckPeriod: pgxpool pings idle connections to detect stale ones.
	cfg.HealthCheckPeriod = time.Minute

	pool, err := pgxpool.NewWithConfig(ctx, cfg)
	if err != nil {
		return nil, fmt.Errorf("create pool: %w", err)
	}

	// Ping immediately to fail fast at startup rather than on first request.
	if err := pool.Ping(ctx); err != nil {
		pool.Close()
		return nil, fmt.Errorf("ping db: %w", err)
	}
	return pool, nil
}

// ===========================================================================
// QUERIES (what sqlc generates — written here manually for illustration)
// sqlc reads .sql files like:
//
//	-- name: GetUser :one
//	SELECT id, name, email FROM users WHERE id = $1;
//
// and produces the function below. The advantage: the SQL is plain SQL
// (readable, optimisable), and the Go is fully type-safe (no interface{}).
// ===========================================================================

// Queries holds a reference to the DB pool and provides typed query methods.
// In a sqlc project this struct and all methods are generated automatically.
type Queries struct {
	pool *pgxpool.Pool
}

// GetUser fetches a single user by primary key.
// db.QueryRow returns a Row regardless of whether there is a result;
// the error surfaces during Scan() via pgx.ErrNoRows.
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	// Always pass ctx so the caller can impose a deadline.
	row := q.pool.QueryRow(ctx,
		`SELECT id, name, email FROM users WHERE id = $1`,
		id, // $1 — parameterised, never interpolated (SQL injection prevention)
	)
	var u User
	// Scan maps each column in SELECT order to a Go variable by pointer.
	// Column order must match exactly — this is what sqlc enforces at
	// code-generation time; mistakes are caught at compile time, not runtime.
	if err := row.Scan(&u.ID, &u.Name, &u.Email); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			// Translate driver-specific error to a domain-level sentinel.
			return User{}, fmt.Errorf("user %d: %w", id, ErrNotFound)
		}
		return User{}, fmt.Errorf("scan user: %w", err)
	}
	return u, nil
}

// ErrNotFound is a domain sentinel for missing entities.
// Callers use errors.Is(err, ErrNotFound) — not string matching.
var ErrNotFound = errors.New("not found")

// ListUsers returns all users. rows.Close() is CRITICAL — it returns the
// connection to the pool. Forgetting it drains the pool silently.
func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.pool.Query(ctx,
		`SELECT id, name, email FROM users ORDER BY id`,
	)
	if err != nil {
		return nil, fmt.Errorf("query users: %w", err)
	}
	defer rows.Close() // always defer immediately after checking the error

	var users []User
	for rows.Next() { // advances the cursor; returns false when exhausted
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Email); err != nil {
			return nil, fmt.Errorf("scan row: %w", err)
		}
		users = append(users, u)
	}
	// rows.Err() captures any error that stopped iteration early (network
	// failure, context cancellation). Must check AFTER the loop.
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("rows error: %w", err)
	}
	return users, nil
}

// CreateUser inserts a user and returns the new row (RETURNING clause).
// ExecContext is used for writes that don't return rows; QueryRow is
// used here because RETURNING gives us the generated ID.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.pool.QueryRow(ctx,
		`INSERT INTO users (name, email) VALUES ($1, $2)
		 RETURNING id, name, email`,
		arg.Name, arg.Email,
	)
	var u User
	if err := row.Scan(&u.ID, &u.Name, &u.Email); err != nil {
		return User{}, fmt.Errorf("create user: %w", err)
	}
	return u, nil
}

// ===========================================================================
// TRANSACTIONS
// Pattern: Begin → defer Rollback → do work → Commit.
// The deferred Rollback is a safety net:
//   - If Commit succeeds: Rollback returns pgx.ErrTxClosed (harmless).
//   - If any step fails and we return early: Rollback undoes partial writes.
//   - If a panic occurs: deferred Rollback still runs (cleanup on panic).
// ===========================================================================

// TransferFunds moves amount from one account to another atomically.
// Both updates succeed or neither does — no partial transfers.
func TransferFunds(ctx context.Context, pool *pgxpool.Pool, arg TransferParams) error {
	// Begin acquires a connection from the pool for the transaction's lifetime.
	tx, err := pool.Begin(ctx)
	if err != nil {
		return fmt.Errorf("begin tx: %w", err)
	}
	// Deferred rollback: runs if we return before Commit (error or panic).
	// pgx.ErrTxClosed is returned after a successful Commit — ignore it.
	defer func() {
		if rbErr := tx.Rollback(ctx); rbErr != nil && !errors.Is(rbErr, pgx.ErrTxClosed) {
			slog.Error("rollback failed", "err", rbErr)
		}
	}()

	// Debit the sender account.
	_, err = tx.Exec(ctx,
		`UPDATE accounts SET balance = balance - $1 WHERE id = $2 AND balance >= $1`,
		arg.Amount, arg.FromAccountID,
	)
	if err != nil {
		return fmt.Errorf("debit account %d: %w", arg.FromAccountID, err)
	}

	// Credit the receiver account.
	_, err = tx.Exec(ctx,
		`UPDATE accounts SET balance = balance + $1 WHERE id = $2`,
		arg.Amount, arg.ToAccountID,
	)
	if err != nil {
		return fmt.Errorf("credit account %d: %w", arg.ToAccountID, err)
	}

	// Audit log inside the same transaction — rolls back with the rest
	// if anything above failed, maintaining audit integrity.
	_, err = tx.Exec(ctx,
		`INSERT INTO transfers (from_id, to_id, amount) VALUES ($1, $2, $3)`,
		arg.FromAccountID, arg.ToAccountID, arg.Amount,
	)
	if err != nil {
		return fmt.Errorf("insert transfer log: %w", err)
	}

	// Commit atomically applies all three statements.
	if err := tx.Commit(ctx); err != nil {
		return fmt.Errorf("commit tx: %w", err)
	}
	return nil
}

// ===========================================================================
// gRPC — SERVER SIDE
//
// Proto3 definition (users.proto) — field numbers are PERMANENT:
//
//   syntax = "proto3";
//   package user.v1;
//
//   service UserService {
//     rpc GetUser(GetUserRequest) returns (UserResponse);
//     rpc ListUsers(ListUsersRequest) returns (stream UserResponse);
//     rpc CreateUser(CreateUserRequest) returns (UserResponse);
//   }
//
//   message GetUserRequest  { int64 id = 1; }
//   message ListUsersRequest {}
//   message CreateUserRequest { string name = 1; string email = 2; }
//   message UserResponse { int64 id = 1; string name = 2; string email = 3; }
//
// Generate: protoc --go_out=. --go-grpc_out=. users.proto
// The generated code defines UserServiceServer interface + RegisterFn.
// ===========================================================================

// UserServiceServer implements the gRPC service interface generated by protoc.
// In a real project: embed pb.UnimplementedUserServiceServer for forward
// compatibility (new proto methods won't break compilation).
type UserServiceServer struct {
	queries *Queries
	// pb.UnimplementedUserServiceServer  ← embed in real projects
}

// GetUser implements UserService.GetUser unary RPC.
// status.Errorf maps domain errors to gRPC status codes that the client
// can inspect with status.Code(err).
func (s *UserServiceServer) GetUser(ctx context.Context, req *GetUserRequest) (*UserResponse, error) {
	// Validate input — return codes.InvalidArgument, not codes.Internal
	if req.Id <= 0 {
		return nil, status.Errorf(codes.InvalidArgument, "id must be > 0, got %d", req.Id)
	}

	// Add a per-RPC deadline; don't trust the caller to always set one.
	ctx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel() // always cancel to release resources

	user, err := s.queries.GetUser(ctx, req.Id)
	if err != nil {
		if errors.Is(err, ErrNotFound) {
			// codes.NotFound → HTTP 404 via gRPC-Gateway
			return nil, status.Errorf(codes.NotFound, "user %d not found", req.Id)
		}
		// codes.Internal → never leak internal error details to the client
		slog.Error("GetUser DB error", "id", req.Id, "err", err)
		return nil, status.Error(codes.Internal, "internal server error")
	}
	return userToProto(user), nil
}

// ListUsers implements a server-streaming RPC.
// The server sends UserResponse messages one at a time; the client
// receives them in a loop until EOF. Good for large result sets —
// avoids buffering all rows in memory.
func (s *UserServiceServer) ListUsers(req *ListUsersRequest, stream UserServiceListUsersServer) error {
	users, err := s.queries.ListUsers(stream.Context())
	if err != nil {
		return status.Error(codes.Internal, "fetch users failed")
	}
	for _, u := range users {
		// Send each user individually over the stream
		if err := stream.Send(userToProto(u)); err != nil {
			// Client disconnected or stream broken
			return status.Errorf(codes.Unavailable, "stream send: %v", err)
		}
	}
	return nil // EOF signals end of stream to the client
}

// userToProto maps the domain User to the proto-generated UserResponse.
func userToProto(u User) *UserResponse {
	return &UserResponse{Id: u.ID, Name: u.Name, Email: u.Email}
}

// ===========================================================================
// gRPC INTERCEPTORS (middleware for gRPC)
// Interceptors wrap every unary call — equivalent to HTTP middleware.
// Registered on grpc.NewServer; apply to every method on all services.
// ===========================================================================

// LoggingInterceptor logs every RPC with method name, duration, and status.
// Place this outermost so it captures errors from all other interceptors.
func LoggingInterceptor(
	ctx context.Context,
	req any,
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (any, error) {
	start := time.Now()
	resp, err := handler(ctx, req) // call the actual handler (or next interceptor)
	code := codes.OK
	if err != nil {
		code = status.Code(err) // extract gRPC status code from the error
	}
	slog.Info("gRPC request",
		"method", info.FullMethod,
		"code", code.String(),
		"duration_ms", time.Since(start).Milliseconds(),
	)
	return resp, err
}

// AuthInterceptor validates a Bearer token from gRPC metadata.
// Metadata is the gRPC equivalent of HTTP headers.
func AuthInterceptor(
	ctx context.Context,
	req any,
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (any, error) {
	// Skip auth for health-check methods (if any)
	if info.FullMethod == "/grpc.health.v1.Health/Check" {
		return handler(ctx, req)
	}

	// Extract metadata from context (set by gRPC transport from client headers)
	md, ok := metadata.FromIncomingContext(ctx)
	if !ok {
		return nil, status.Error(codes.Unauthenticated, "missing metadata")
	}

	values := md.Get("authorization") // gRPC metadata keys are lowercase
	if len(values) == 0 {
		return nil, status.Error(codes.Unauthenticated, "missing authorization header")
	}

	token := values[0]
	if !validateBearerToken(token) {
		return nil, status.Error(codes.Unauthenticated, "invalid token")
	}

	return handler(ctx, req) // token valid — proceed to the actual handler
}

// RecoveryInterceptor catches panics and converts them to gRPC Internal errors.
// Without this, a panic in a handler crashes the goroutine silently (in gRPC
// the connection is dropped; the client sees a transport error).
func RecoveryInterceptor(
	ctx context.Context,
	req any,
	info *grpc.UnaryServerInfo,
	handler grpc.UnaryHandler,
) (resp any, err error) {
	defer func() {
		if r := recover(); r != nil {
			slog.Error("panic in gRPC handler", "method", info.FullMethod, "panic", r)
			err = status.Errorf(codes.Internal, "internal error")
		}
	}()
	return handler(ctx, req)
}

func validateBearerToken(token string) bool {
	// Stub: replace with JWT verification or opaque token lookup.
	return token == "Bearer valid-token" // demo only
}

// ===========================================================================
// gRPC SERVER — wiring interceptors and starting the listener
// ===========================================================================

// StartGRPCServer creates and starts the gRPC server.
// Interceptors are chained in order: Recovery → Auth → Logging → Handler.
// The outermost interceptor (listed first in ChainUnaryInterceptor) runs first.
func StartGRPCServer(pool *pgxpool.Pool) error {
	// Chain multiple interceptors — executed in declaration order.
	srv := grpc.NewServer(
		grpc.ChainUnaryInterceptor(
			RecoveryInterceptor, // must be outermost to catch panics in auth/logging
			AuthInterceptor,
			LoggingInterceptor,
		),
	)

	userSvc := &UserServiceServer{queries: &Queries{pool: pool}}
	// In a real project: pb.RegisterUserServiceServer(srv, userSvc)
	_ = userSvc // suppress unused warning in this standalone file

	// TCP listener on all interfaces — in K8s, the Service routes to this port.
	lis, err := net.Listen("tcp", ":50051")
	if err != nil {
		return fmt.Errorf("listen: %w", err)
	}

	slog.Info("gRPC server listening", "addr", lis.Addr())
	// Serve blocks until the server is stopped (or an error occurs).
	return srv.Serve(lis)
}

// ===========================================================================
// gRPC CLIENT — how another service calls this one
// ===========================================================================

// NewGRPCClient creates a gRPC client connection to the user service.
// grpc.NewClient does NOT establish the TCP connection immediately;
// it dials lazily on the first RPC. Use WithBlock() + timeout if you
// need to verify connectivity at startup.
func NewGRPCClient(addr string) (*grpc.ClientConn, error) {
	conn, err := grpc.NewClient(
		addr, // e.g. "user-service:50051" (K8s DNS name)
		grpc.WithInsecure(), // dev only — use grpc.WithTransportCredentials in prod
	)
	if err != nil {
		return nil, fmt.Errorf("dial %s: %w", addr, err)
	}
	return conn, nil
}

// CallGetUser shows how a client calls the GetUser RPC.
func CallGetUser(conn *grpc.ClientConn, userID int64) (*UserResponse, error) {
	// In real code: client := pb.NewUserServiceClient(conn)
	// Always set a deadline — without one, the call can block indefinitely
	// if the server is slow or unreachable.
	ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
	defer cancel()

	// Attach auth token as metadata (gRPC's equivalent of HTTP Authorization header)
	ctx = metadata.AppendToOutgoingContext(ctx, "authorization", "Bearer valid-token")

	// client.GetUser(ctx, &pb.GetUserRequest{Id: userID})
	_ = ctx
	return &UserResponse{Id: userID, Name: "stub"}, nil // placeholder
}

// ===========================================================================
// PLACEHOLDER TYPES (replace with protoc-generated types in a real project)
// These mirror the generated structs from users.proto.
// ===========================================================================

type GetUserRequest struct{ Id int64 }
type ListUsersRequest struct{}
type UserResponse struct {
	Id    int64
	Name  string
	Email string
}

// UserServiceListUsersServer is the generated stream interface for ListUsers.
type UserServiceListUsersServer interface {
	Send(*UserResponse) error
	Context() context.Context
}

// ===========================================================================
// MAIN — wire everything together and start
// ===========================================================================

func main() {
	// Read DSN from env — never hardcode credentials.
	dsn := os.Getenv("DATABASE_URL")
	if dsn == "" {
		log.Fatal("DATABASE_URL env var is required")
	}

	ctx := context.Background()

	// Create the connection pool; fail fast if DB is unreachable.
	pool, err := NewPool(ctx, dsn)
	if err != nil {
		log.Fatalf("connect to db: %v", err)
	}
	defer pool.Close() // return all connections to PostgreSQL on shutdown

	// Start the gRPC server (blocks until error or signal).
	if err := StartGRPCServer(pool); err != nil {
		log.Fatalf("gRPC server: %v", err)
	}
}
